language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - extra
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
    - ./gradlew build dependencies || true

before_install:
    - chmod +x gradlew

branches:
  only:
    - master